[tool.black]
line-length = 88
target_version = ['py37']
include ='''
(
    ^/__tests__/
  | ^/src/
)
'''
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''